### ISSUE TITLE
Review portable storage implementation.

### ISSUE THREAD

**Issue by jeandudey** [xmr-rs/xmr#2]
Checklist:

- [x] Do this implementation binary output matches the one in Monero's epee?
- [x] Add test's to verify this it's compatible with Monero.
- [x] Also, do this implementation follow the same semantics found in Monero (how portable storage
sections are created)? 
- [x] Do types have good names that reason about theri meaning?
    - [x] WTF is `ToUnderlying`?, explore an approach using `std` library.
- [x] Is it using `failure` optimally?
- [x] Review `Bytes` and `BufMut` usage.
- [ ] Test the parser never crashes.
